Feature/connect profile and settings to state
Nawigacja-SGGW/mobileapp pull request #43
Opened 2024-12-10 21:59 UTC by mpygruu

Podpięcie widoków profilu i settingsów do warstwy logiki.

Dodatkowo widok zmieniania preferencji trasy bo brakowało a jest w designach.

2024-12-13 21:29 UTC, heisenshark requested changes

2024-12-13 21:29 UTC, heisenshark commented on src/app/changeRoutePreferencesView.tsx
> +  { label: t('settings.bike'), value: RoutePreference.Bike },
settings.walk i settings.bike nie ma w tłumaczeniach

2024-12-14 16:59 UTC, mpygruu commented on src/app/changeRoutePreferencesView.tsx
> +  { label: t('settings.bike'), value: RoutePreference.Bike },
Dobra bo inna libka była używana tu akurat, już poprawiłem, działa.

2024-12-15 16:44 UTC, heisenshark approved these changes

2024-12-15 16:44 UTC, merged